# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(315, 202)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.data_acquisition_rate_value = QtWidgets.QSpinBox(Dialog)
        self.data_acquisition_rate_value.setMaximum(999)
        self.data_acquisition_rate_value.setProperty("value", 10)
        self.data_acquisition_rate_value.setObjectName("data_acquisition_rate_value")
        self.gridLayout.addWidget(self.data_acquisition_rate_value, 2, 2, 1, 1)
        self.start_value = QtWidgets.QTimeEdit(Dialog)
        self.start_value.setObjectName("start_value")
        self.gridLayout.addWidget(self.start_value, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 3)
        self.dialog_button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.dialog_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.dialog_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialog_button_box.setObjectName("dialog_button_box")
        self.gridLayout.addWidget(self.dialog_button_box, 6, 0, 1, 3)
        self.data_acquisition_rate_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.data_acquisition_rate_label.setFont(font)
        self.data_acquisition_rate_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.data_acquisition_rate_label.setObjectName("data_acquisition_rate_label")
        self.gridLayout.addWidget(self.data_acquisition_rate_label, 2, 0, 1, 2)
        self.start_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_label.setFont(font)
        self.start_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_label.setObjectName("start_label")
        self.gridLayout.addWidget(self.start_label, 0, 0, 1, 2)
        self.file_name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.file_name_label.setFont(font)
        self.file_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.file_name_label.setObjectName("file_name_label")
        self.gridLayout.addWidget(self.file_name_label, 5, 0, 1, 1)
        self.end_value = QtWidgets.QTimeEdit(Dialog)
        self.end_value.setObjectName("end_value")
        self.gridLayout.addWidget(self.end_value, 1, 2, 1, 1)
        self.end_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.end_label.setFont(font)
        self.end_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.end_label.setObjectName("end_label")
        self.gridLayout.addWidget(self.end_label, 1, 0, 1, 2)
        self.file_name_value = QtWidgets.QLineEdit(Dialog)
        self.file_name_value.setObjectName("file_name_value")
        self.gridLayout.addWidget(self.file_name_value, 5, 1, 1, 2)
        self.data_acquisition_rate_label.setBuddy(self.data_acquisition_rate_value)
        self.start_label.setBuddy(self.start_value)
        self.end_label.setBuddy(self.end_value)

        self.retranslateUi(Dialog)
        self.dialog_button_box.accepted.connect(Dialog.accept)
        self.dialog_button_box.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.start_value, self.end_value)
        Dialog.setTabOrder(self.end_value, self.data_acquisition_rate_value)
        Dialog.setTabOrder(self.data_acquisition_rate_value, self.file_name_value)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_value.setDisplayFormat(_translate("Dialog", "hh:mm:ss"))
        self.data_acquisition_rate_label.setText(_translate("Dialog", "Data Acquisition Rate"))
        self.start_label.setText(_translate("Dialog", "Starting RA"))
        self.file_name_label.setText(_translate("Dialog", "File name"))
        self.end_value.setDisplayFormat(_translate("Dialog", "hh:mm:ss"))
        self.end_label.setText(_translate("Dialog", "Ending RA"))
