# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 320)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.declination_group_box = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.declination_group_box.setFont(font)
        self.declination_group_box.setObjectName("declination_group_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.declination_group_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.south_label = QtWidgets.QLabel(self.declination_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.south_label.setFont(font)
        self.south_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.south_label.setObjectName("south_label")
        self.gridLayout_5.addWidget(self.south_label, 0, 0, 1, 1)
        self.north_label = QtWidgets.QLabel(self.declination_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.north_label.setFont(font)
        self.north_label.setObjectName("north_label")
        self.gridLayout_5.addWidget(self.north_label, 0, 2, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.declination_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMinimum(-25)
        self.horizontalSlider.setMaximum(95)
        self.horizontalSlider.setSingleStep(5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_5.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.declination_group_box, 1, 0, 1, 2)
        self.button_frame = QtWidgets.QFrame(Dialog)
        self.button_frame.setObjectName("button_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.button_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.close_button = QtWidgets.QPushButton(self.button_frame)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.gridLayout_2.addWidget(self.close_button, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.button_frame, 2, 0, 1, 2)
        self.signal_group_box = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.signal_group_box.setFont(font)
        self.signal_group_box.setObjectName("signal_group_box")
        self.gridLayout = QtWidgets.QGridLayout(self.signal_group_box)
        self.gridLayout.setObjectName("gridLayout")
        self.variance_dial = QtWidgets.QDial(self.signal_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.variance_dial.setFont(font)
        self.variance_dial.setMinimum(-10)
        self.variance_dial.setMaximum(10)
        self.variance_dial.setWrapping(False)
        self.variance_dial.setNotchTarget(1.0)
        self.variance_dial.setNotchesVisible(True)
        self.variance_dial.setObjectName("variance_dial")
        self.gridLayout.addWidget(self.variance_dial, 1, 1, 1, 1)
        self.noise_dial = QtWidgets.QDial(self.signal_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.noise_dial.setFont(font)
        self.noise_dial.setMinimum(-10)
        self.noise_dial.setMaximum(10)
        self.noise_dial.setWrapping(False)
        self.noise_dial.setNotchTarget(1.0)
        self.noise_dial.setNotchesVisible(True)
        self.noise_dial.setObjectName("noise_dial")
        self.gridLayout.addWidget(self.noise_dial, 1, 2, 1, 1)
        self.polarization_dial = QtWidgets.QDial(self.signal_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.polarization_dial.setFont(font)
        self.polarization_dial.setMinimum(-10)
        self.polarization_dial.setMaximum(10)
        self.polarization_dial.setWrapping(False)
        self.polarization_dial.setNotchTarget(1.0)
        self.polarization_dial.setNotchesVisible(True)
        self.polarization_dial.setObjectName("polarization_dial")
        self.gridLayout.addWidget(self.polarization_dial, 1, 3, 1, 1)
        self.variance_label = QtWidgets.QLabel(self.signal_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.variance_label.setFont(font)
        self.variance_label.setAlignment(QtCore.Qt.AlignCenter)
        self.variance_label.setObjectName("variance_label")
        self.gridLayout.addWidget(self.variance_label, 0, 1, 1, 1)
        self.polarization_label = QtWidgets.QLabel(self.signal_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.polarization_label.setFont(font)
        self.polarization_label.setAlignment(QtCore.Qt.AlignCenter)
        self.polarization_label.setObjectName("polarization_label")
        self.gridLayout.addWidget(self.polarization_label, 0, 2, 1, 1)
        self.noise_label = QtWidgets.QLabel(self.signal_group_box)
        font = QtGui.QFont()
        font.setFamily("Iosevka Aile")
        self.noise_label.setFont(font)
        self.noise_label.setAlignment(QtCore.Qt.AlignCenter)
        self.noise_label.setObjectName("noise_label")
        self.gridLayout.addWidget(self.noise_label, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.signal_group_box, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.close_button.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.variance_dial, self.noise_dial)
        Dialog.setTabOrder(self.noise_dial, self.polarization_dial)
        Dialog.setTabOrder(self.polarization_dial, self.horizontalSlider)
        Dialog.setTabOrder(self.horizontalSlider, self.close_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Test"))
        self.declination_group_box.setTitle(_translate("Dialog", "Declination"))
        self.south_label.setText(_translate("Dialog", "South"))
        self.north_label.setText(_translate("Dialog", "North"))
        self.close_button.setText(_translate("Dialog", "Close"))
        self.signal_group_box.setTitle(_translate("Dialog", "Signal"))
        self.variance_label.setText(_translate("Dialog", "Variance"))
        self.polarization_label.setText(_translate("Dialog", "Polarization"))
        self.noise_label.setText(_translate("Dialog", "Noise"))
